### ISSUE TITLE
importing assets is missing from lang ref.

### ISSUE THREAD

**Issue by abakobo** [mx2DocsCommunity/monkey2#38]

**Comment by arawkins** [comment]
Just finished a first draft: https://github.com/arawkins/monkey2/blob/wipdocs/modules/monkey/docs/language/assets-management.md

Will review it again tomorrow with fresh eyes :)

**Comment by abakobo** [comment]
cool, happy to lean how it works. Should the file types depending on platforms be in this "asset management" topic?

**Comment by arawkins** [comment]
Sure, that makes sense. I will add a section for it.

**Comment by arawkins** [comment]
Ok, I revised the doc, and added in the file types stuff. I copied the supported file types from the monkey-x docs; I'm assuming they are the same for monkey2. If not I can update them.
